import React from "react";

export default function privacyPolicy() {
  return (
    <section className="default-page">
      <div className="custom-container">
        <h1>Privacy & Policy</h1>
        <div className="page-content">
          <p className="about-description">
            This Privacy Policy constitutes an electronic record in terms of the
            Information Technology Act, 2000 and rules made there under. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>
          <p className="about-description">
            We at VisitMadhisland Private Limited “VisitMadhisland” value the
            trust placed in us by the visitors to our website and the users of
            our services and therefore insist upon the highest standards for
            secure transactions and customer information privacy. We are
            committed to protect the information that you may share with us as a
            user. This Privacy Policy describes the information that we collect
            from you as part of the normal operation of our services and what
            may happen to that information. By accessing or using this website,
            you expressly consent to our use and disclosure of your personal
            information in accordance with this Privacy Policy. This Privacy
            Policy is incorporated into and is subject to the terms mentioned in
            the Terms and Conditions of Use.
          </p>
          <p className="about-description">
            At the outset, we wish to inform you that this Privacy Policy is
            subject to change without prior notification or intimation to the
            visitors or users of the website. Hence, you are advised to
            regularly check for any amendments or updates to this Privacy
          </p>
          <ol>
            <li>
              <h3>THE INFORMATION COLLECTED BY US</h3>
              <p className="about-description">
                In general, you can browse this website without revealing any
                personal information about yourself. However, in the event you
                desire to make any reservations through our website, we will
                require information such as your name, contact number, email id,
                billing information, bank account details and such other
                personal information.
              </p>
              <p className="about-description">
                Wherever possible, we indicate whether the information to be
                provided is optional or mandatory and always provide you the
                option to not provide information by choosing not to use a
                particular service or feature on the website
              </p>
              <p className="about-description">
                You are requested to provide accurate and correct information.
                We shall not be responsible for the authenticity of the personal
                information or data supplied by the users and any inconvenience
                caused because of the same.
              </p>
              <p className="about-description">
                Based on your use of our services and on your behaviour on this
                website, we may automatically track certain information about
                you. We use this information to do internal research on our
                users' demographics, interests and behaviour to better
                understand, protect and serve our users. We also monitor
                customer traffic patterns and website use, which enables us to
                improve the service we provide. We assure you that we will
                collect only such information as is necessary and relevant to us
                to provide you with the services available on the Site.
              </p>
            </li>
            <li>
              <h3>PERSONAL INFORMATION</h3>
              <p className="about-description">
                Personal Information is that information which, we may collect
                from you and is capable of identifying you, such as:
              </p>
              <ul>
                <li>Name and Gender</li>
                <li>Phone Number</li>
                <li>E-mail address</li>
                <li>Contact Address</li>
                <li>Password</li>
                <li>
                  financial information such as Bank Account, credit card, debit
                  card information or other payment instrument details for the
                  purpose of processing payments,
                </li>
                <li>physical, physiological and mental health condition</li>
                <li>
                  Other details such as biometric information, Sexual
                  orientation, medical records and history
                </li>
              </ul>
              <p className="about-description">
                Note: Your financial information is held, retained and processed
                by a third party Payment Gateway, namely, Razorpay having their
                registered office at Roc-Banglore. Razorpay is obligated to
                maintain confidentiality of your financial information under
                various applicable laws and under an agreement with us. However,
                we shall not be liable for any actions of the third party
                Payment Gateway in breach of their confidentiality obligations
                and disclosure of your financial information. Being returning
                guests to our properties on a regular basis, It is sole duty of
                you to inform us if any of your personal information, needs to
                be updated with us. Upon suspect regarding Booking, we may
                contact you at any time.
              </p>
            </li>
            <li>
              <h3>COOKIES</h3>
              <p className="about-description">
                "Cookies” are small files placed on your hard drive that assist
                us in providing our services. We use Cookies on certain pages of
                the website to help analyze our web page flow, measure
                promotional effectiveness, and promote trust and safety. Cookies
                help us provide information that is targeted to your interests.
                They also enable the browser to remember information specific to
                a given user and thereby allow you to enter your password less
                frequently during a session. Most cookies are session cookies,
                meaning that they are automatically deleted from your hard drive
                at the end of a session.
              </p>
              <p className="about-description">
                You may decline the use of cookies if your browser permits the
                same. However, in that case you may not be able to use certain
                features of this website and you may be required to re-enter
                your password more frequently during a session.
              </p>
              <p className="about-description">
                You may, at times, encounter cookies or other similar data
                collection devices on certain pages of the Site that are placed
                by third parties. We do not control the use of cookies by third
                parties.
              </p>
            </li>
            <li>
              <h3>OFFERS AND UPDATES</h3>
              <p className="about-description">
                When you provide us with your email address at the time of any
                reservation, you agree to allow us to contact you about offers
                and updates with respect to the website and the services
                offered. In order to evaluate your use of our services, we may
                track which functions of our website you use most frequently.
                This information will help us provide you with only the most
                relevant and useful information displayed on the website and
                about our services. If you decide at any time that you no longer
                wish to receive communications from us you may opt out or
                unsubscribe yourself from the facility by selecting the
                unsubscribe feature from our website or follow the link on our
                communicational emails.
              </p>
            </li>
            <li>
              <h3>USE OF THE INFORMATION COLLECTED BY US </h3>
              <p className="about-description">
                We assure you that we use the personal information you provide
                us only as appropriate and required in the ordinary course of
                business.
              </p>
              <p className="about-description">
                We use your personal information to allow us to process your
                reservation on the website, to provide you with improved
                services, to contact you when it is needed by telephone and
                e-mail and to assist you, to share the same with trusted third
                parties, if so required.
              </p>
              <p className="about-description">
                Further, the relevant information may be used by us to
                communicate with you on any matter relating to your reservation
                and / or to communicate the details thereof and of other
                services displayed on this website.
              </p>
              <p className="about-description">
                We may also use your personal information to resolve disputes,
                troubleshoot problems, measure consumer interest in the services
                provided by us, inform you about online and offline offers,
                services, and updates; customize your experience; detect and
                protect us against error, fraud and other criminal activity;
                enforce the Terms and Conditions of Use; and as otherwise
                described to you at the time of collection. The information may
                also be used to improve our marketing and promotional efforts,
                to analyse site usage, improve and customize the website’s
                content, layout, and services. These uses improve the website
                and help us to tailor it to meet your needs so as to provide you
                with a smooth, efficient, safe and customized experience while
                using the Site.
              </p>
            </li>
            <li>
              <h3>SHARING OF INFORMATION WITH THIRD PARTIES</h3>
              <p className="about-description">
                Your information may be shared with third parties in the
                following circumstances:
                <br />
                <b>6.1</b> When trusted third parties (such as our accountants,
                credit card processing companies, hotels, Government officials
                etc.) are performing a service for us or for you, we may provide
                them with the information collected about you only to the extent
                they need it to perform that particular service.
                <br />
                <b> 6.2</b> If we reorganize our company or sell or lease our
                business, the new entity, owner or operator will assume any
                rights we have in respect of our information about you. We
                assure you that we will obtain reasonable assurances that your
                privacy will continue to be respected;
                <br />
                <b>6.3</b> If we have to help investigate, prevent or take
                action regarding unlawful and illegal activities, suspected
                fraud, potential threat to the safety or security of any person
                or organization or property or asset or rights of the Website
                from unauthorized use or misuse of the Website, violations of
                our terms and conditions or to defend against legal
                claims/proceedings;
                <br />
                <b>6.4</b> Upon occurrence of special circumstances detailed
                hereunder –
                <br />
                <b>6.4.1</b> to respond to summons, court orders, judicial
                proceedings, or other legal processes;
                <br />
                <b>6.4.2</b> to enforce the terms of the website Terms and
                Conditions of Use or the terms of this Privacy Policy;
                <br />
                <b>6.4.3</b> to cooperate and assist authorized agencies for
                interception or monitoring or decryptions as mentioned in the
                Information Technology (Procedure and Safeguards for
                Interception, Monitoring and Decryption of Information) Rules,
                2009.
                <br />
                <b> 6.4.4</b> to assist and cooperate with the authorized
                agencies for the monitoring and collection of traffic data or
                information generated, transmitted, received or stored, in
                accordance with the Information Technology (Procedure and
                Safeguard for Monitoring and Collecting Traffic Data or
                Information) Rules, 2009.
                <br />
                <b>6.5</b> We may use third parties that we refer to as internal
                service providers to facilitate or outsource one or more aspects
                of the business, product and service operations that we provide
                to you on this website and therefore we may provide some of your
                personal information directly to these internal service
                providers. These internal service providers are subject to
                confidentiality agreements with us and other legal restrictions
                that prohibit their use of the information we provide them for
                any other purpose except to facilitate the specific outsourced
                website related operation, unless you have explicitly agreed or
                given your prior permission to them for additional uses. Subject
                to this policy, we assure you that we will share your Personal
                Information only if we have your consent or deemed consent to do
                so or if we are compelled by law (including court orders) to do
                so.
              </p>
            </li>
            <li>
              <h3>DISCLOSURE OF INFORMATION </h3>
              <p className="about-description">
                <b> 7.1</b> Advertisements: The website may contain third party
                advertisements and wherever you disclose information to any form
                of an advertiser so displayed on the website, the information is
                simultaneously collected by us and the advertiser. The
                information is used by us in accordance with the terms of this
                Privacy Policy and is used by the advertiser as per the
                advertiser’s prevalent privacy policy. Since we do not control
                the privacy practices of these advertisers or third party, you
                should evaluate their practices before deciding to provide the
                said information. We shall not be responsible for the
                information provided by you to such advertisers or collected by
                such advertisers from you.
                <br />
                <b>7.2</b> Links to other sites: The website may contain links
                to other websites that may collect information about you. We are
                not responsible for the privacy practices or the content of such
                linked websites
              </p>
            </li>
            <li>
              <h3>PROTECTING YOUR INFORMATION </h3>
              <p className="about-description">
                We are committed to protect the information provided by you. We
                have adopted various managerial, technical, physical and other
                security measures to protect the information provided by you.
                For Instance, we use encryption while transmission of
                information sensitive to you between your and our system and
                allowing only authorized persons for permitted business
                functions to access your personal information etc.
              </p>
            </li>
            <li>
              <h3>SECURITY MEASURES </h3>
              <p className="about-description">
                In furtherance of the confidentiality with which we treat your
                information, we assure you that to prevent unauthorized access,
                maintain data accuracy, and ensure correct use of information,
                we will employ reasonable security practices and procedures and
                current Internet security methods and technologies in compliance
                with Information Technology Act, 2000 and rules made there
                under.
                <br />
                Moreover, we restrict access of personal information to our
                employees, contractors and agents who need to know that
                information in order to operate, develop or improve our
                services. These individuals are bound by confidentiality
                obligations and may be subject to discipline, including
                termination and criminal prosecution, if they fail to meet these
                obligations.
                <br />
                However, although we use industry standard practices to protect
                your privacy, we cannot ensure that all of your private
                communications and other personal information will never be
                disclosed in ways not otherwise described in this Privacy
                Policy. By way of example (without limiting the foregoing), we
                may be forced to disclose personal information to the government
                or third parties under certain circumstances, third parties may
                unlawfully intercept or access transmissions or private
                communications or users may abuse or misuse your personal
                information that they collect from the website.
              </p>
            </li>
            <li>
              <h3>APPLICABLE LAW & JURISDICTION </h3>
              <p className="about-description">
                This website is created and controlled by VisitMadhisland and
                shall be governed by the laws of India. The courts in Mumbai
                shall have exclusive jurisdiction in respect of all the terms,
                conditions and disclaimers.
              </p>
            </li>
            <li>
              <h3>PRIVACY AT HOTELS & LIKE PROPERTIES </h3>
              <p className="about-description">
                VisitMadhisland is a hotel and like property booking platform
                and does not operate, control or manage any such hotel or like
                property. VisitMadhisland shall not be responsible in any manner
                for any of your privacy issues at hotel or like property booked
                through our website or our mobile App.
              </p>
            </li>
            <li>
              <h3>CHANGES TO THIS PRIVACY POLICY </h3>
              <p className="about-description">
                We may update this Privacy Policy in the future when we feel to
                do so. Any changes we may make to our Privacy Policy in the
                future will be posted on this page. You should access our
                privacy policy regularly in order to familiarize yourself with
                the latest policy.
              </p>
            </li>
            <li>
              <h3>GRIEVANCE POLICY </h3>
              <p className="about-description">
                VisitMadhisland strongly believes in a transparent approach to
                its users. This policy aims at minimizing instances of customer
                complaints, grievances and disappointments via channelized
                approach, review and redressal. You can file a grievance if you
                are disappointed or have issues in respect of services rendered
                by VisitMadhisland. You can give your grievance through email or
                snail mail to the Grievance officer of VisitMadhisland. The
                email address at which you can send your grievances is
                rajsharmaq123@gmail.com .
              </p>
              <p className="about-description">
                The grievances can also be sent by Snail Mail on the following
                address:-
                <br />
                <b>Mr. raj sharma</b>
                <br />
                <b>Grievance officer, </b>
                br
                <b>Madhisland Mumbai </b>
              </p>
            </li>
            <li>
              <h3>A SPECIAL NOTE ABOUT MINORS </h3>
              <p className="about-description">
                Persons under the age of 18 are not eligible to use the
                accommodation reservation services on our Site. Minors can
                normally accompany their parent(s) or legal custodian(s) who
                have booked an accommodation.
              </p>
            </li>
            <li>
              <h3>USING THE MOBILE PHONE AND TABLET APPS (THE “MOBILE APPS”</h3>
              <p className="about-description">
                While using our app, the information is collected in the same
                way and for the same purposes as we do when you use this
                Website.
                <br />
                In addition, we also use some other information that is
                collected automatically when you use our Mobile Apps.
                Specifically:
                <br />
                We collect information about Mobile App functionality that you
                access and use. This allows identification of those areas of the
                Mobile App that are of interest to our customers. The
                information we collect for this purpose restricts us to identify
                you directly.
                <br />
                When you use a Mobile App, you can choose to allow access to
                your current location using GPS or similar technologies, in
                order to identify nearby hotels, airports, or other service
                providers. If you choose to allow access, this location data may
                be collected as a part of search requests logged by our servers.
                You can turn off access to your location at any time through
                your phone settings menu.
                <br />
                In the event the Mobile App crashes or hangs, it will send us
                error-reporting information. In this way we can investigate the
                error for stability of the Mobile App. As part of these error
                reports, the Mobile App sends us information about the mobile
                device type and version, the UID, the time the error occurred,
                the feature being used and the state of the application when the
                error occurred. This information is not used for any purpose
                other than investigating and remedying the error.
                <br />
                You can always control what information you want to receive from
                Mobile App. You can do so firstly by modifying settings of the
                Mobile App under its setting menu and secondly by changing the
                settings of your mobile device. Alternatively, or else you can
                remove the Mobile App from your mobile device entirely and
                access our services through our Website.
              </p>
            </li>
            <li>
              <h3>EXPRESS CONSENT </h3>
              <p className="about-description">
                By accessing this page or using this website, you expressly
                consent to our use and disclosure of your personal information
                in accordance with this Privacy Policy and Indian laws.
                <br />
                <br />
                Note: Headings are for reference purposes only and in no way
                define, limit, construe or describe the scope or extent of such
                section.
              </p>
            </li>
          </ol>
        </div>
      </div>
    </section>
  );
}
